name: Hilde Hogendoorn
favicon: null
layout_spectrum: 0.6800552916247398
typography_spectrum: 0.7790994355455041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6567027629353106
  lightness: 0.9593696244992316
  saturation: 0.6751711105462164
  rhythmicContrast: 0.6653142825234681
purpose: []
